// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjS4UTJJwzPOqwAMkPJGLCxxMOp-o8gs',
    appId: '1:493960901641:web:314ef3a6e5badbd0a5b4d8',
    messagingSenderId: '493960901641',
    projectId: 'app16-ac545',
    authDomain: 'app16-ac545.firebaseapp.com',
    storageBucket: 'app16-ac545.appspot.com',
    measurementId: 'G-YKEKWTPWLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSJY3p23Sq7sZWpYrANf1eB6EHP7G6_I',
    appId: '1:493960901641:android:ca382fcfa41b0b81a5b4d8',
    messagingSenderId: '493960901641',
    projectId: 'app16-ac545',
    storageBucket: 'app16-ac545.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW7hsQjvWwevh73g7x4ih5XY86iXrYar0',
    appId: '1:493960901641:ios:6e0ceb271097a6e3a5b4d8',
    messagingSenderId: '493960901641',
    projectId: 'app16-ac545',
    storageBucket: 'app16-ac545.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW7hsQjvWwevh73g7x4ih5XY86iXrYar0',
    appId: '1:493960901641:ios:6e0ceb271097a6e3a5b4d8',
    messagingSenderId: '493960901641',
    projectId: 'app16-ac545',
    storageBucket: 'app16-ac545.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjS4UTJJwzPOqwAMkPJGLCxxMOp-o8gs',
    appId: '1:493960901641:web:8cb01704826d89d9a5b4d8',
    messagingSenderId: '493960901641',
    projectId: 'app16-ac545',
    authDomain: 'app16-ac545.firebaseapp.com',
    storageBucket: 'app16-ac545.appspot.com',
    measurementId: 'G-4RRS2LTMR0',
  );
}
